chore: make SSR work with compatibility mode 21.7 and below (#106)
Remove destructuring, which causes the following error when enabling SSR
on a sandbox with CM 21.7:
```
SyntaxError: invalid object initializer
in controller Search
```


Small unrelated changed: moved the `in_stock` declaration to the 2nd
section and removed the `attribute` field, as it's handled by a custom
function