fix: productModelCustomizer compatibility mode (#112)
In older Compatibility Mode versions, the jobs are throwing the
following error:
`TypeError: Cannot find function includes in object
primary_category_id,in_stock,price.
(int_algolia/cartridge/scripts/algolia/customization/productModelCustomizer.js#108)`

Use `indexOf` instead of `includes` to make it compatible.
Tested on CM 18.10.